### ISSUE TITLE
environment.yml has old and unused dependencies.

### ISSUE THREAD

**Issue by merterden98** [mims-harvard/gnn-tutorials#7]
`conda env create -f environment.yml` fails when installing on latest version of anaconda. Some libraries like `libgfortran` are not supported. I'm also not sure why packages like `pymongo` exist in `dependencies`. Is there any way we can do a little bit of cleanup here?

**Comment by marinkaz** [comment]
Great point! You are right, we haven't refreshed environment.yml for a while now. Would you be willing to create a pull request addressing some of these issues?

**Comment by merterden98** [comment]
Can do! Currently facing installation issues, but once I have all the requirements fulfilled I'll submit a PR for a new environment (after making sure it still works with the examples)

**Comment by marinkaz** [comment]
Thank you!
